### ISSUE TITLE
DTSTART/END should not have TZID when UTC

### ISSUE THREAD

**Issue by alfiedotwtf** [icalendar/icalendar#109] opened 2015-02-11 02:37 UTC
Hi,

I've stumbled on a calendar event which looks like it may be been generated by this package:

    PRODID:icalendar-ruby
    ...
    DTSTART;TZID=UTC:20150209T153000
    DTEND;TZID=UTC:20150209T154500

The problem here is that DTSTART and DTEND should not have a TZID parameter when the value is UTC (RFC5545):

    3.2.19.  Time Zone Identifier

    The following are examples of this property parameter:

      DTSTART;TZID=America/New_York:19980119T020000
      DTEND;TZID=America/New_York:19980119T030000

      The "TZID" property parameter MUST NOT be applied to DATE
      properties and DATE-TIME or TIME properties whose time values are
      specified in UTC.

Instead, the times should be Zulu suffixed:

    3.3.5.  Date-Time

    FORM #2: DATE WITH UTC TIME

    The date with UTC time, or absolute time, is identified by a LATIN
    CAPITAL LETTER Z suffix character, the UTC designator, appended to
    the time value.  For example, the following represents January 19,
    1998, at 0700 UTC:

      19980119T070000Z

    The "TZID" property parameter MUST NOT be applied to DATE-TIME
    properties whose time values are specified in UTC.

**Comment by juggy** [comment] 2015-03-27 00:37
Had this problem too. You should be able to create an event in UTC, without specifying any timezone. Currently the calendar applications think the event is in the local user timezone because it is not suffixed.

**Comment by alfiedotwtf** [comment] 2015-03-27 13:30
Hey @juggy,

Sorry I'm not the one who created the calendar data. One of our users imported a calendar event which was generated by this library. Just thought I'd report upstream :)

**Comment by rahearn** [comment] 2015-04-08 03:40
Hmm. Any idea the version they used to generate? We _should_ be properly leaving off the TZID param and appending 'Z' for UTC times.

Using the current version:

```
>> e = Icalendar::Event.new
=> #<Icalendar::Event:0x007fcd9c1dbdb8 @name="event", @ical_name="VEVENT", @custom_components={}, @custom_properties={}, @dtstamp=Wed, 08 Apr 2015 03:38:33 UTC +00:00, @uid="6eadf83d-80de-45b1-9c31-982c0538cc71">
>> e.dtstart = "20150209T153000Z"
=> "20150209T153000Z"
>> e.to_ical
=> "BEGIN:VEVENT\r\nDTSTAMP:20150408T033833Z\r\nUID:6eadf83d-80de-45b1-9c31-982c0538cc71\r\nDTSTART:20150209T153000Z\r\nEND:VEVENT\r\n"
```

**Comment by alfiedotwtf** [comment] 2015-04-08 23:59
@rahearn sorry, no. There's no versioning on the vendor line.

If it's fixed in master, feel free to close this bug. I'll reopen if I see another case in the wild.

**Comment by rahearn** [comment] 2015-04-09 14:21
This might have been caused by the case sensitive nature of `ical_params`

Tracking the fix in #116 so closing this issue.

**Closed by rahearn** 2015-04-09 14:21 UTC

**Comment by alfiedotwtf** [comment] 2015-04-10 03:25
Thanks @rahearn!

**Comment by gmcnaughton** [comment] 2015-07-06 15:01
I hit a similar issue because I assumed that dtstart/dtend could take `Time` objects.  However, if I feed them a Time object that's in UTC, the 'Z' zulu suffix is not added:

    >> e = Icalendar::Event.new
    => #<Icalendar::Event:0x007ff779cb7bb8 @name="event", @ical_name="VEVENT", @custom_components={}, @custom_properties={}, @dtstamp=Mon, 06 Jul 2015 14:54:50 UTC +00:00, @uid="86c542cf-8c4a-4d61-a07b-437a152293ff">
    >> e.dtstart = Time.now.utc    
    => Mon, 06 Jul 2015 14:55:03 +0000
    >> e.to_ical
    => "BEGIN:VEVENT\r\nDTSTAMP:20150706T145450Z\r\nUID:86c542cf-8c4a-4d61-a07b-437a152293ff\r\nDTSTART:20150706T145503\r\nEND:VEVENT\r\n"

To get UTC dtstart/dtend, do I need to format the times to strings manually before passing them in?
